import type { QuizQuestion } from '@/lib/types';

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    text: "Какие ваши любимые жанры аниме? (Выберите до 3)",
    type: 'checkbox',
    fieldName: 'favoriteGenres',
    options: [
      { value: 'Action', label: 'Экшен' },
      { value: 'Adventure', label: 'Приключения' },
      { value: 'Comedy', label: 'Комедия' },
      { value: 'Drama', label: 'Драма' },
      { value: 'Fantasy', label: 'Фэнтези' },
      { value: 'Horror', label: 'Ужасы' },
      { value: 'Mystery', label: 'Детектив' },
      { value: 'Romance', label: 'Романтика' },
      { value: 'Sci-Fi', label: 'Научная фантастика' },
      { value: 'Slice of Life', label: 'Повседневность' },
      { value: 'Sports', label: 'Спорт' },
      { value: 'Supernatural', label: 'Сверхъестественное' },
    ],
    required: true,
  },
  {
    id: 'q2',
    text: "Какой сюжет вы предпочитаете?",
    type: 'radio',
    fieldName: 'plotPreference',
    options: [
      { value: 'Fast-paced and action-packed', label: 'Динамичный и насыщенный действиями' },
      { value: 'Slow-burn with deep character development', label: 'Медленно развивающийся с глубокой проработкой персонажей' },
      { value: 'Complex and thought-provoking', label: 'Сложный и заставляющий задуматься' },
      { value: 'Lighthearted and episodic', label: 'Легкий и эпизодический' },
    ],
    required: true,
  },
  {
    id: 'q3',
    text: "Какой художественный стиль вам нравится больше всего?",
    type: 'radio',
    fieldName: 'artStyle',
    options: [
      { value: 'Classic (80s-90s style)', label: 'Классический (стиль 80-х-90-х)' },
      { value: 'Modern and crisp', label: 'Современный и четкий' },
      { value: 'Unique and stylized (e.g., Monogatari, Jojo)', label: 'Уникальный и стилизованный (например, Monogatari, Jojo)' },
      { value: 'Art style is not a major factor', label: 'Художественный стиль не является важным фактором' },
    ],
    required: true,
  },
  {
    id: 'q4',
    text: "Какой длительности в идеале должен быть аниме-сериал?",
    type: 'radio',
    fieldName: 'seriesLength',
    options: [
      { value: 'Short (1-12 episodes)', label: 'Короткий (1-12 серий)' },
      { value: 'Medium (13-26 episodes)', label: 'Средний (13-26 серий)' },
      { value: 'Long (27-50+ episodes)', label: 'Длинный (27-50+ серий)' },
      { value: 'Movies or OVAs are great too', label: 'Фильмы или OVA тоже отлично подходят' },
    ],
    required: true,
  },
  {
    id: 'q5',
    text: "Какие темы вам нравятся? (Выберите до 3)",
    type: 'checkbox',
    fieldName: 'preferredThemes',
    options: [
      { value: 'Coming-of-age', label: 'Взросление' },
      { value: 'Dystopian futures', label: 'Антиутопическое будущее' },
      { value: 'Epic battles / Warfare', label: 'Эпические битвы / Война' },
      { value: 'Found family / Friendship', label: 'Обретенная семья / Дружба' },
      { value: 'Magical worlds / Isekai', label: 'Магические миры / Исекай' },
      { value: 'Philosophical questions', label: 'Философские вопросы' },
      { value: 'Post-apocalyptic survival', label: 'Постапокалиптическое выживание' },
      { value: 'Psychological / Thriller', label: 'Психологическое / Триллер' },
      { value: 'Time travel / Alternate realities', label: 'Путешествия во времени / Альтернативные реальности' },
    ],
  },
  {
    id: 'q6',
    text: "Какую общую атмосферу вы предпочитаете в аниме?",
    type: 'radio',
    fieldName: 'preferredTone',
    options: [
      { value: 'Mostly serious with some comedic relief', label: 'В основном серьезную с элементами комедии' },
      { value: 'A balanced mix of serious and comedic elements', label: 'Сбалансированное сочетание серьезных и комедийных элементов' },
      { value: 'Mostly comedic with occasional serious moments', label: 'В основном комедийную с редкими серьезными моментами' },
      { value: 'Purely lighthearted and fun', label: 'Исключительно легкую и веселую' },
    ],
    required: true,
  },
  {
    id: 'q7',
    text: "Какой из этих сеттингов вас больше всего привлекает?",
    type: 'radio',
    fieldName: 'preferredSetting',
    options: [
      { value: 'Historical (e.g., feudal Japan, ancient civilizations)', label: 'Исторический (например, феодальная Япония, древние цивилизации)' },
      { value: 'Contemporary / Modern-day world', label: 'Современный мир' },
      { value: 'Futuristic cityscape / Sci-fi world', label: 'Футуристический город / Научно-фантастический мир' },
      { value: 'A completely fantastical realm', label: 'Полностью вымышленный фэнтезийный мир' },
      { value: 'Outer space / Space opera', label: 'Космос / Космическая опера' },
    ],
    required: true,
  },
  {
    id: 'q8',
    text: "Есть ли элементы, которых вы категорически хотите ИЗБЕЖАТЬ? (Выберите все подходящие варианты)",
    type: 'checkbox',
    fieldName: 'elementsToAvoid',
    options: [
      { value: 'Excessive gore / violence', label: 'Чрезмерная жестокость / насилие' },
      { value: 'Excessive fan service / ecchi', label: 'Чрезмерный фансервис / этти' },
      { value: 'Very slow pacing', label: 'Очень медленный темп повествования' },
      { value: 'Overly complex plots / politics', label: 'Слишком сложные сюжеты / политика' },
      { value: 'Ambiguous or cliffhanger endings', label: 'Неоднозначные или обрывающиеся на самом интересном месте концовки' },
      { value: 'None, I am open to anything', label: 'Нет, я открыт(а) для всего'},
    ],
  },
  {
    id: 'q9',
    text: "За каких главных героев вы обычно болеете?",
    type: 'radio',
    fieldName: 'protagonistType',
    options: [
      { value: 'The overpowered hero who dominates', label: 'Сверхсильный герой, который доминирует' },
      { value: 'The underdog who grows stronger through challenges', label: 'Аутсайдер, который становится сильнее через испытания' },
      { value: 'The anti-hero with questionable morals but clear goals', label: 'Антигерой с сомнительной моралью, но четкими целями' },
      { value: 'An ordinary person thrust into extraordinary circumstances', label: 'Обычный человек, попавший в необычные обстоятельства' },
      { value: 'A group/ensemble cast rather than a single focus', label: 'Группа/ансамбль персонажей, а не один главный герой'}
    ],
    required: true,
  },
  {
    id: 'q10',
    text: "Если можете, назовите аниме, которое вам очень понравилось. (Необязательно)",
    type: 'text',
    fieldName: 'previouslyEnjoyedAnime',
    description: "Это поможет ИИ лучше понять ваш вкус."
  },
];
